### PR TITLE
No internet dependency (addressing #2109)

### PR DESCRIPTION
**Pull request by matthiasg**
As was mentioned in #2109, the build should have the least amount (preferably none) of outside dependencies which require an internet connection or any other dynamically updated code from outside sources that is not part of the distribution.

Primary Reason:

Handling of SOUPs ([Software of Unknown Provenance](https://www.johner-institute.com/articles/software-iec-62304/soup-and-ots/)) is integral to getting certifications and having potential software changes from the outside makes it much harder.

Of course one can argue that `workbox` is version locked on what is in essence a CDN, but depending on the auditing process this could lead to unnecessary complexity in proving how this is ascertained (there are ways of course).

Secondary Reason:

Also a standalone viewing library for medical images should not be required to have a dependency on a working Internet connection as many internal medical networks are disconnected from that and would at the very least require exemptions to be put into place just for the sake of using OHIF.

### CODE REVIEW

**Comment by matthiasg** [comment]
I did realize in this pull request I also included a new .gitignore rule to exclude *.js.map files which are generated during the build process. This could potentially be done in a separate pull request if so desired.

**Comment by matthiasg** [comment]
It is just waiting for the pull request to be merged :)

**Comment by matthiasg** [comment]
Nobody ? ;) 

We appreciate the amount of work that goes into reviewing even smaller PR as this. Is there anything we can contribute to ensure more resources are available ?

**Comment by swederik** [comment]
Thanks! So sorry for the ridiculously long reply to this @matthiasg!

**Pull request merged**
