### PR TITLE
fix/openresty keycloak

### PR DESCRIPTION
**Pull request by sedghi**
### Context

Should be able to follow this recipe up until troubleshooting 

https://docs.ohif.org/2.0-deprecated/deployment/recipes/user-account-control#troubleshooting

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by jbocce** [comment]
The changes look great. Thanks so much for making this work.

I tried the recipe and I was successful.

I added the headers to allow for `SharedArrayBuffer` usage. Perhaps you want to give this a try to make sure it works for you?

Do we want to bring back these docs? https://docs.ohif.org/2.0-deprecated/deployment/recipes/user-account-control/?

Also note that this PR addresses issue #3637

**Comment by SachidanandAlle** [comment]
Verified from myside.. (all steps mentioned in the setup section - sign-in + upload study, open basic viewer)
https://docs.ohif.org/2.0-deprecated/deployment/recipes/user-account-control/#setup

Thanks :)

**Comment by sedghi** [comment]
@SachidanandAlle Noice!

**Comment by SachidanandAlle** [comment]
Quick question. 
How to get username (logged in user) in viewer?  Are we setting some cookie?

**Comment by jbocce** [comment]
> Quick question. How to get username (logged in user) in viewer? Are we setting some cookie?

The `AuthenticationService` has a `getUser`. Does that give you what you want?

**Comment by SachidanandAlle** [comment]
`getUser()` gives me lot more
Thanks for the quick answer.  I got what I needed :)

```json
{
    "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwMmc3T0stZnlOMGZWanJNRWltQUJlZjVWV19XenI1eWdnc24xazBLNXM4In0.eyJqdGkiOiI4ZjNlODhkNS05Y2U3LTRhOWQtYmI3NS0zOWJlYTBlNDJmMjEiLCJleHAiOjE2OTUwNjYwMDAsIm5iZiI6MCwiaWF0IjoxNjk1MDY1NzAwLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xL2F1dGgvcmVhbG1zL29oaWYiLCJhdWQiOiJvaGlmLXZpZXdlciIsInN1YiI6ImU5Mzk4ZDVjLTQwZWYtNGE3ZC1iMjg3LWFhYzBlMDBlMjE5ZSIsInR5cCI6IklEIiwiYXpwIjoib2hpZi12aWV3ZXIiLCJhdXRoX3RpbWUiOjE2OTUwNjU0NDcsInNlc3Npb25fc3RhdGUiOiJhOWNkMTdkNS05NTkwLTQ3ZDYtYTFkZi1hZDc0MTVlM2M2NTIiLCJhY3IiOiIwIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJUZXN0Rk5VIFRlc3RMTiIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoiVGVzdEZOVSIsImZhbWlseV9uYW1lIjoiVGVzdExOIiwiZW1haWwiOiJ0ZXN0QG52LmNvbSJ9.E3lJLJfnok93sOOpPIr1wOGXJWYZoukD3JYlc9u-RKXXGEXNL4tVIp3_WVAX1pejGF6RDlCERA3Ed8npTmYvECQ2GrDRDy2AXW1ychfS8H1ZVo7xibbTVbzZ5XXsSa-JBoPbHByT-SfMUPb8XPOLaLQFwfQlDxgOSCT1TrQJaMXbkV1MdbKAnus4TIyRvboasgZi5D1LxYqVeIxpd72ZCICDNwcc3mbzVm41G_sgfKJWMxQioYozPF8225gQ2gMpmO9PI6ZBWtGDgPCb2cihNUCt3xH7WXXfH8-rQ7Z3IYCmrqOvkqbM0Qj2vHO-RNSmtJpFwVRpt2QLlOY0C4oUvw",
    "session_state": "a9cd17d5-9590-47d6-a1df-ad7415e3c652",
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwMmc3T0stZnlOMGZWanJNRWltQUJlZjVWV19XenI1eWdnc24xazBLNXM4In0.eyJqdGkiOiIxYmQ2YTQ0Yi0wMWE3LTQ5MTMtOTc1My1iNTQ3ODdmMTQ0OWQiLCJleHAiOjE2OTUwNjYwMDAsIm5iZiI6MCwiaWF0IjoxNjk1MDY1NzAwLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xL2F1dGgvcmVhbG1zL29oaWYiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiZTkzOThkNWMtNDBlZi00YTdkLWIyODctYWFjMGUwMGUyMTllIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoib2hpZi12aWV3ZXIiLCJhdXRoX3RpbWUiOjE2OTUwNjU0NDcsInNlc3Npb25fc3RhdGUiOiJhOWNkMTdkNS05NTkwLTQ3ZDYtYTFkZi1hZDc0MTVlM2M2NTIiLCJhY3IiOiIwIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly8xMjcuMC4wLjEiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6Im9wZW5pZCBlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJUZXN0Rk5VIFRlc3RMTiIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoiVGVzdEZOVSIsImZhbWlseV9uYW1lIjoiVGVzdExOIiwiZW1haWwiOiJ0ZXN0QG52LmNvbSJ9.ZodCXsLQSIkyaxjciJ0pNpIo8b_CviRf03O_YIJSqmw2EQxIZxhfIuGV-3WdNWU42hGapZNOehJqSeVpw4hEAOV-gshnay8EfYIqZmjyWyQqg7ACYJep4rDmRkzXk1vnKEQxSe4llctwtov6jvnRGjnDPWsx4EWVvFXIOUeHxkiXPQcCqWxW9Aj0mx8mSoJOj1IxIf0-TwWXamAVgvmSvZRuVGoRBT1DMDD9v9MFx8y5p8KSPr3chEcIqJtMrq5_z5LFNWtsRlE_Yz4D3bCRGtD1kkSehOk_a-qgpvfqSLcHmpOSrXmIMsj1PadxL6d5ELwxXRNdnSBhXTQ1EFQHtQ",
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJkNTc1NjhiNC1lNDU1LTQ4OTMtYjM3NC00MGQyZDkwNDU3NzIifQ.eyJqdGkiOiJiYTFjZWU3MS1kNmJhLTQ0MzItYTBjOC1jYzIzNmU5ODg1NjgiLCJleHAiOjE2OTUwNjc1MDAsIm5iZiI6MCwiaWF0IjoxNjk1MDY1NzAwLCJpc3MiOiJodHRwOi8vMTI3LjAuMC4xL2F1dGgvcmVhbG1zL29oaWYiLCJhdWQiOiJodHRwOi8vMTI3LjAuMC4xL2F1dGgvcmVhbG1zL29oaWYiLCJzdWIiOiJlOTM5OGQ1Yy00MGVmLTRhN2QtYjI4Ny1hYWMwZTAwZTIxOWUiLCJ0eXAiOiJSZWZyZXNoIiwiYXpwIjoib2hpZi12aWV3ZXIiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJhOWNkMTdkNS05NTkwLTQ3ZDYtYTFkZi1hZDc0MTVlM2M2NTIiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUifQ.JFxxDq8YP2G4TIBC0cJj4mBcnxMDM9oeJyn5fAGIUh4",
    "token_type": "bearer",
    "scope": "openid email profile",
    "profile": {
        "jti": "8f3e88d5-9ce7-4a9d-bb75-39bea0e42f21",
        "sub": "e9398d5c-40ef-4a7d-b287-aac0e00e219e",
        "typ": "ID",
        "azp": "ohif-viewer",
        "auth_time": 1695065447,
        "session_state": "a9cd17d5-9590-47d6-a1df-ad7415e3c652",
        "acr": "0",
        "email_verified": true,
        "name": "TestFNU TestLN",
        "preferred_username": "test",
        "given_name": "TestFNU",
        "family_name": "TestLN",
        "email": "test@nv.com"
    },
    "expires_at": 1695066000
}
```

**Comment by SachidanandAlle** [comment]
I don't know if this is related.. 
but I am seeing lot more error messages on console (nothing blocking on basic functionality..)

> I am using merged code for 2 branches (fix/openresty-keycloak and feat/segmentation-mode)
I am not sure this error is leaking from where..

Screenshot from 2023-09-18 19-43-07

**Review by jbocce — APPROVED** [review]
Approved.

**Comment by AskAlice** [comment]
was deleting the docker-compose examples intended? because you have a dead link in the docs at https://docs.ohif.org/configuration/dataSources/dicom-web#orthanc-learn-more

and the README in the .docker folder no longer makes any sense

**Comment by sedghi** [comment]
Which part does not makes sense

**Comment by AskAlice** [comment]
> Which part does not makes sense

https://github.com/OHIF/Viewers/tree/master/.docker

there is no compose yaml so the instructions don't coorelate with any file in the repo

**Comment by sedghi** [comment]
@AskAlice Search for dockerfile you see some in the recipe section, also you can look at here as well https://docs.ohif.org/deployment/

**Comment by AskAlice** [comment]
> @AskAlice Search for dockerfile you see some in the recipe section, also you can look at here as well [docs.ohif.org/deployment](https://docs.ohif.org/deployment/)

yeah understood and i saw it in git diff from this merge, just wondered if it was intentional that it's harder to find now :+1:

**Pull request merged**
