### PR TITLE
fix: use defaultTool if failed to use same tool in new hanging protoc…

### PR DESCRIPTION
**Pull request by dxlin**
fix: use defaultTool if failed to use same tool in new hanging protocol stage

### Context
Briefly reviewed to resolve crosshair misalignment issue from:
https://github.com/OHIF/Viewers/issues/3911

Was not able to locate root cause of misalignment, may have to do with button/tool state but didn't try to investigate further due to development in toolbar:
https://github.com/OHIF/Viewers/issues/3927

It does appear turning off crosshair and re-enabling after 2nd entry into MPR mode resolves the issue.

### Changes & Results
Simplest workaround was to default to a default tool when switching to primaryToolBeforeHPChange doesn't work.

Crosshair now off when switching back into MPR and initial misalignment will not be visible to end user.

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
I'm revamping the toolbar very soon, all of these problems will go away, I think we wait for my changes and later decide on this

**Comment by jenny-hm-lee** [comment]
Hi @sedghi 
what is the update on this PR?  
Is the toolbar changes finished, can we help testing?

**Comment by sedghi** [comment]
we have revamped the toolbar and this is not applicable anymore

**Comment by jenny-hm-lee** [comment]
@sedghi , this PR aims to fix issue #3911 , which still exist on OHIF dev viewer.  @dxlin will update the PR, as the toolbar has changed a lot since.  
Please reopen this PR.

**Pull request closed without merging**
