### PR TITLE
fix: Responsive design for worklist height

### PR DESCRIPTION
**Pull request by wayfarer3130**
### Context

Makes the worklist height responsive rather than being a fixed size, making it easier to see items.

### Changes & Results

Changed the height/min-height of the worklist to be a responsive design.
Renumbered the expansion numbering for series to be 0 based.

### Testing

Run the automated tests.
Search/display studies.

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Review by sedghi — CHANGES_REQUESTED** [review]
I don't see any changes in the responsiveness, and it has even altered the alignment, as you can see in the screenshot below.

CleanShot 2024-05-22 at 10 25 28@2x

**Comment by wayfarer3130** [comment]
The layout will automatically scroll/change the height of the contents of the table results - see 
Minimum Height:
image

Medium height:
image

Tall
image


Very tall
image

**Comment by wayfarer3130** [comment]
Note how you get a scrollbar on the table contents, and it will expand to use as much of the height, rather than losing all the controls at the bottom, as in:
image

I've fixed the loss of the space on the right hand side by making the scrollbar optional.

**Comment by sedghi** [comment]
We are creating a completely new design for tablets and mobile devices very soon. Can we hold off on moving forward with this PR?

**Pull request closed without merging**
