### PR TITLE
feat: MeasurementPanel Update

### PR DESCRIPTION
**Pull request by GitanjaliChhetri**
### Context
Fixes https://github.com/OHIF/Viewers/issues/3100 and https://github.com/OHIF/Viewers/issues/3108.

### Changes & Results
1. User can now select a specific SR series from the Measurement select panel. By default the first SR series is selected.
Number of applicable SR series is also indicated.

https://user-images.githubusercontent.com/112136540/214475515-7cada06f-7c71-4c27-bd9c-fe7ea6564413.mp4

2. DICOM SR parsing logic is now updated to add labels from the children of a content item.
Coding scheme designators have also been updated https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_8.3.html
https://dicom.nema.org/medical/dicom/current/output/chtml/part16/chapter_O.html#:~:text=363698007,Finding%20site%20(attribute)

https://user-images.githubusercontent.com/112136540/214475836-7e8e1c6c-3dc0-4bf0-8565-27fffb21eacc.mp4

### Testing

Tested with the new SR dataset provided https://github.com/OHIF/Viewers/issues/3108#issuecomment-1382083821, and any dataset with multiple SRs.

#### PR

- [x] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [x] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [x] "OS: Windows 10
- [x] "Node version: v16.17.0
- [x] "Browser: Chrome 

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Review by igoroctaviano — APPROVED** [review]
LGTM 🎖️ 

The data you have used to test is public? 
Can you share links to the input/original series + SR?

**Comment by GitanjaliChhetri** [comment]
Thank you for reviewing @igoroctaviano!
Sure, you can find the data sets here:
1. new SR dataset https://github.com/OHIF/Viewers/issues/3108#issuecomment-1382083821, and 
2. multiple SRs https://www.dropbox.com/s/ftbwbnrq98npmb2/OHIF_slice_level_annotation_issue_09_16_22.zip?dl=0

**Comment by fedorov** [comment]
@igoroctaviano you can also access SR test data from the single place in the IDC testing inventory here: https://docs.google.com/spreadsheets/d/12n1AWUynEFPatmNUphyW9IhOHaePN2jNUrzzjLunJtg/edit?usp=sharing. If you have feedback on how to make it more convenient to use, please let me know!

**Comment by GitanjaliChhetri** [comment]
Closing this one as the change is going to IDC fork only. (https://github.com/ImagingDataCommons/Viewers/pull/178)

**Pull request closed without merging**
