### PR TITLE
fix: Set VTK viewport as active by interaction 

### LINKED ISSUE #1078: User is unable to set the VTK viewport as the ActiveViewport by interaction.
- Open a study containing a CT
- Select a series with 40+ images
- Enable 2D MPR
- Attempt to interact with vtkViewport
- Viewport does not become "active" (see border around viewport)
- [ ] **Should have E2E test**

xtH9UOPXkY

### PR DESCRIPTION
**Pull request by rodrigolabs**
- It's currently working only for click events using the available tools.
  - it worked only for the `onClick` which means that it waits for the `mousedown` and `mouseup` interaction to perform the `setViewportActive`. -- would be good to work using `onMouseDown`.

- `onScroll/onWheel` events didn’t work -- maybe some internal interaction with scrolling in `react-vtkjs-viewport` is swallowing the scroll event (?)

## Preview

vtk-viewport

---

Fixes #1078

### CODE REVIEW

**Comment by dannyrb** [comment]
@rodrigolabs, I'd rather this not become inactive. What are the next steps here?

**Comment by rodrigolabs** [comment]
> @rodrigolabs, I'd rather this not become inactive. What are the next steps here?

@dannyrb, with this current implementation, we're able to set a viewport as active only by clicking on it. I'd have to spend more time trying to figure out how to activate a viewport by scrolling. As I mentioned before, it seems that some internal interaction with `onScroll` in `react-vtkjs-viewport` is swallowing our scroll implementations.

**Comment by dannyrb** [comment]
I've made some progress here: https://github.com/OHIF/react-vtkjs-viewport/pull/81
Even if the above is merged, there's quite a bit of song and dance to complete this ticket.

**Comment by JamesAPetts** [comment]
https://github.com/OHIF/react-vtkjs-viewport/pull/81 gives a scroll event to work off for this issue:

> onScroll/onWheel events didn’t work -- maybe some internal interaction with scrolling in react-vtkjs-viewport is swallowing the scroll event (?)

**Comment by dannyrb** [comment]
HOC CommandsManager --> OHIFVtkViewport --> ConnectedVtkViewport --> VtkViewport --> View2D

So much wrapping.

- VTKViewport
  - Support for `onScroll`
  - Support for `onClick`
- ConnectedVtkViewport
  - Handles `onCreated` "api" object capture (escape hatch)
  - Connects `setViewportActive` and `setViewportSpecificData`
- OHIFVtkViewport
  - Some volume creation/management (should eventually be kicked up a layer)
  - Exposes/sets remaining props
- HOC
  - Uses `commandsManager` in module registration to set `onScroll` fn prop

^ I'm sure there's some room for consolidation there. This feels needlessly wrappy, and hard to guess why each layer exists at a glance.

**Comment by dannyrb** [comment]
CC: @JamesAPetts, ready for review.
Click + Scroll set VTK Viewports active

**Comment by JamesAPetts** [comment]
Hey, I'm getting an error if you try to scroll prior to using the crosshairs. I think this is because the value isn't cached yet, i'll make a quick fix for it in `react-vtkjs-viewport`.

**Comment by JamesAPetts** [comment]
> https://github.com/OHIF/react-vtkjs-viewport/pull/90

Updated here. When the new react-vtkjs-viewport dist is released you can pull it in.

**Pull request merged**
