### PR TITLE
Re #2164: load overlapping segmentation WIP

### PR DESCRIPTION
**Pull request by Punzo**
WIP: this is a work in progress PR

based on the logic implemented in https://github.com/dcmjs-org/dcmjs/pull/155 as described in point (2) in https://github.com/OHIF/Viewers/issues/2164#issuecomment-732240664.

dcmjs can return an array of LabelMaps if segments are overlapping. In this PR we load the labelMaps in the segmentation display and we define as active the first one https://github.com/OHIF/Viewers/compare/master...Punzo:IDC2164?expand=1#diff-0835569e2ca4d01ae2d66254833e8ab800b668a0cdce905e21c127e05c775f9bR105

Still to do:

- the UI does not allow to change the active label Map. It would be necessary to have in the UI, widget to see all the loaded labelMaps and pick the active one, so that one can change between:

image
image

- at the moment, when using MPR mode (vtk.js) only the active one will be passed from cornerstone to vtk.

- memory consumption can be large and we should add a warning.

### CODE REVIEW

**Comment by Punzo** [comment]
@igoroctaviano for point 1 I was thinking to have in the UI something like this:
image

to pick the active labelMap of teh segmentation. Please let me know what do you think about it.

**Comment by fedorov** [comment]
Can we skip the selector of the active label map, by default show segments from all of the label maps in the viewer, and show the combined list of all segments from all label maps under the segmentation selector?

I do not like the concept of the labelmap selector available to the user.

**Comment by fedorov** [comment]
Sorry, closed by accident!

**Comment by Punzo** [comment]
> Sorry, closed by accident!

no problem.

> by default show segments from all of the label maps in the viewer, and show the combined list of all segments from all label maps under the segmentation selector?

A) for doing this properly, we would need cornerstone/vtk/OIHF UI to handle multiple active labelMaps (for a given segmentation item). This would need major changes in the OIHF UI and cornerstonetools rendering (e.g. https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/eventListeners/internals/renderSegmentationFill.js) and how the segmentation is copied from cornerstone to vtk. 

B) with the current infrastructure is actually not possible without having bugs in the UI. An example: if you have two labelMaps as in screenshots (https://github.com/OHIF/Viewers/pull/2185#issue-527522637), we can set the first labelMap (segments 1,2,3,6) as active and the second labelMap (segments 4 and 5) as inactive. Then, we could force to show anyway all the segments controls for both the label Maps as:

image

but the UI controls for segments 4 and 5 will not work. Moreover, in vtk things will be broken, because only the the active label map will be copied in vtk, and therefore only the segments of the active labelmap will be visualized. 

@igoroctaviano if you have any idea (better than https://github.com/OHIF/Viewers/pull/2185#issuecomment-733782643), please feel free to comment.

P.S.: note there is a substantial difference as active and non active LabelMap are rendered in cornerstoneTools and this reflects on the OIHF UI: 
image

**Comment by fedorov** [comment]
Thanks for the explanation Davide! I think we will need to brainstorm this at the call on Thursday, and get feedback from @pieper before proceeding with the implementation.

**Comment by Punzo** [comment]
> Thanks for the explanation Davide! I think we will need to brainstorm this at the call on Thursday, and get feedback from @pieper before proceeding with the implementation.

Fine for me :+1:

**Comment by Punzo** [comment]
we can just dynamically swap active label map when the user select the segment

**Comment by Punzo** [comment]
> we can just dynamically swap active label map when the user select the segment **(solutionCornerstone)**

@fedorov @pieper this will be a perfect solution for cornerstone viewport, but I actually forgot that there is an additional issue with VTK (my fault I forgot to talk about it during the meeting): VTK currrently take only the active label map from cornerstone.

We can update the Cornerstone-VTK connection to pass all the labelmaps (not only the active one) to VTK **(solutionVTK)**, but VTK has 3 views and duplicates the volume for each view. This will bring memory issues for sure for large datasets.

So our plan would be to use **(solutionCornerstone)** for cornerstone, and then **(solutionVTK)** for VTK. But in the case there will be memory issue for VTK (based on estimation of number of label maps and size of the volumes < 1-1.5 Gb), we would disable the VTK viewport. What do you think about it?

**Comment by pieper** [comment]
I'd say let's not worry about the triple memory issue, since that will go away once we switch to the off-screen MPR mode.

We do already have some series that cannot be rendered in MPR mode (e.g. the 3000 slice one) so we need to have graceful handling of out-of-memory scenarios anyway.

**Comment by igoroctaviano** [comment]
@Punzo https://github.com/Punzo/Viewers/pull/1 here is the PR to dynamically update the label maps on segment click.

**Comment by Punzo** [comment]
> @Punzo [Punzo#1](https://github.com/Punzo/Viewers/pull/1) here is the PR to dynamically update the label maps on segment click.

tested https://github.com/Punzo/Viewers/pull/1 everything working, great! thanks. I'll merge everything now and I'll update the IDC fork as well.

**Pull request merged**
