### PR TITLE
fix: Reordered to prevent variable access before initialization

### PR DESCRIPTION
**Pull request by matthiasg**
Simple Refactor

Reorders variable assignments in Providers before they are being accessed. Mentioned in https://github.com/OHIF/Viewers/issues/2105

### CODE REVIEW

**Comment by matthiasg** [comment]
Is there a specific reason this Pull Request is not being merged ? Anything I can do ?

**Comment by swederik** [comment]
No reason. The PR looks fine to me. Everyone is just busy at the moment

**Comment by matthiasg** [comment]
@swederik Ok, thanks! We are currently incorporating more of OHIF into our platform and would like to helpout wherever we can if it ensures continuous improvements or an easier certification for medical use. Especially the ability to customize the experience (pluggability, customized layouts, scout linces, tools etc) is high on our agenda.

**Comment by swederik** [comment]
Great! We have an announcement coming about the next version which should make plugability and configuration easier for developers consuming the viewer.

**Pull request merged**
