### PR TITLE
test(visual-regression): Add percy tests and improve coverage

### PR DESCRIPTION
**Pull request by IbrahimCSAE**
Related https://github.com/OHIF/Viewers/issues/4098

### Context

Add visual regression tests

### Changes & Results

Tests added:

- All Advanced hanging protocols
- MPR Crosshairs
- PDF Display
- Segmentation Tools
- SR Hydration
- TMTV Mode
- Video Display

### CODE REVIEW

**Review by sedghi — COMMENTED** [review]
can you not commit testdata?

**Comment by sedghi** [comment]
can you pull master?

**Comment by IbrahimCSAE** [comment]
> can you not commit testdata?

i think I have to so next time the git submodule init is done its at the right commit, I had to do it by hand in my branch, like git pull in testdata.

**Comment by sedghi** [comment]
Can you please take a look at the unstable test in cypress? there is one in the study list that is flacky

**Review by sedghi — APPROVED** [review]

**Pull request merged**
