### PR TITLE
Feature: DIMSE proxy

### PR DESCRIPTION
**Pull request by EmilOJ**
As discussed in #145, this shows how to use the OHIFViewer and a dicomWeb proxy to emulate true DIMSE functionality. OHIF is fully capable of communicating via DIMSE but cannot receive image data over this protocol. 
The process is shown in the following flow chart:

DIMSE proxy flowchart 

The main changes to the OHIF code are:
`OHIFViewer/client/routes.js`: Perform a serverside move request of the selected studies to the PACS server before redirecting to the viewer.

`Packages/ohif-dicom-services/server/DIMSE/DIMSE.js`:
1. Force synchronous execution (with `future.wait()`), so the viewer is not rendered before the C-MOVE is done
2. Initiate a C-MOVE request on the STUDY level with the DicomWeb proxy as destination (the destination is hardcoded as of now). 

I have included a new server config file `config/orthancDIMSEproxy.json` for this setup and a `docker-compose.yml` for setting up a dummy PACS and a DicomWeb proxy using Orthanc for testing. 

For testing, follow this workflow:
1. Start OHIFviewer the old way using the included start script in `OHIFViewer/package.json`
2. Start the two orthanc servers with `OHIFViewer/docker-compose.yml`
3. Upload a DICOM series to the "PACS" server at localhost:8042
4. Open OHIFViewer at localhost:3000, this study should now be in the study list (fetched via DIMSE)
5. Double click the study. The study should now have been moved to the DicomWeb proxy server at localhost:8043 and loaded into OHIF via WADO.

### CODE REVIEW

**Comment by swederik** [comment]
This is super awesome!

I might want to put the docker-compose setup in https://github.com/OHIF/integration-examples instead, but in general it's really cool that this works with so few changes.

**Comment by EmilOJ** [comment]
Absolutely, I agree. I just wanted to include it so you can easily test it out. 

Of course this also breaks the normal DicomWeb-only setup that most people use, so there should be some way of enabling/disabling this functionality.

**Comment by EmilOJ** [comment]
I'm happy to implement any suggestions you have to integrate this.

**Comment by dannyrb** [comment]
@EmilOJ, thank you for such a high quality PR. Many, many users don't take the time to contribute back, so I want you to know that myself and the other maintainers truly appreciate seeing PRs like this.

Unfortunately, I'm going to close this PR. Since this PR was drafted, we've made a shift to a new major version that does not support DIMSE. I've added a `bookmark` tag, as I feel `version 1` users and others may find the content here useful.

**Comment by EmilOJ** [comment]
Just leaving this here for reference for someone less experienced with the tools I mentioned in the PR description.

For step two you need have have docker-compose installed on your system.
https://docs.docker.com/compose/

Then from your terminal go the directory that the `docker-compose.yml` file is in and type the command `docker-compose up` .
This will start two Orthanc PACS servers on your laptop. 
Now you should be able to open your browser and go to localhost:8042
And login to the Orthanc server with credentials:
Username: orthanc
Password: orthanc
(I think this is correct)

Then follow the rest of the steps.
You have to setup the two Orthanc servers in the OHIF viewer (There’s an ‘add server’ or something like that option) just like you did with your DIMSE connection.
I don’t remember the exact configurations Im afraid. But I think that it’s something like below:

image

**Comment by pablosbravo** [comment]
Hi everyone, where is the docker-compose.yml file? I can not  find it

**Comment by sedghi** [comment]
@wayfarer3130

**Pull request closed without merging**
