### PR TITLE
fix: get adapter store picker to show

### PR DESCRIPTION
**Pull request by dannyrb**
image

image

### CODE REVIEW

**Comment by pieper** [comment]
Thanks! LGTM - do you want me to try it out on my sandbox or will you just merge to master?

**Comment by pieper** [comment]
Also when I try to go to this dicom store I get the error pasted below.

https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/breast-diagnosis/dicomStores/breast-diagnosis

image

**Comment by dannyrb** [comment]
@pieper, haha, losanges. I can remove the styling.

I'll try to reproduce and diagnose. You see this issue when selecting with the picker, or only when attempting to visit the route directly?

**Comment by dannyrb** [comment]
@pieper, I must not have access to the same data as you. Despite a different app token than what I use for local debugging, I see the same datasets:

Project: `OHIF Cloud Healthcare` (ohif-cloud-healthcare)

FWIW, I'm able to switch between datasets with what I do have access to. When I try to visit the route you've provided directly, I get a `403` (which we could handle more gracefully as well)

**Comment by pieper** [comment]
@dannyrb you probably need to fill out the form to access the TCIA data:

https://cloud.google.com/healthcare/docs/resources/public-datasets/tcia#cloud-healthcare-api

This will give you access to chc-tcia project dicom stores.  I think it's worth doing since there are a lot of good test datasets there (MR, CT, PET, 4d, etc).

Thanks again for your help with this 👍

**Comment by dannyrb** [comment]
@pieper a couple of odd things are causing that particular dataset to fail. The main culprit being that `getName` for `patientName` is returning an object instead of a string value.

We're also seeing issues where both `modality` and `modalitiesInStudy` are undefined. I'm drafting a small PR that should allow us to handle these situations gracefully. I'll ping you when it's up/merged.

**Comment by pieper** [comment]
@dannyrb did you have any trouble signing up for the tcia datasets?  Andrey also says he can add people to that project directly through our contact at Google.

**Pull request merged**
