### PR TITLE
Bring in rotatable crosshairs.

### PR DESCRIPTION
**Pull request by JamesAPetts**
RE: #2098 

Bring in recent crosshair updates from react-vtkjs-viewport.

### CODE REVIEW

**Comment by salimkanoun** [comment]
Hi, amazing feature ! 

I wonder if the orientation isn't inverted in the preview,

see the screen capture, in the axial view I got the costal axis witch is oriented foward and down.

But the red line that should symbolize by axial view in the saggital view is oriented foward and up

image

**Comment by JamesAPetts** [comment]
Ahh, good catch, I think you are right.

**Comment by JamesAPetts** [comment]
I've moved the react-vtkjs-viewport to a brainscan which makes this much more obvious.

The issue was actually just a trivial error due to SVG and the webgl coordinates being inverted with respect to each other, I've fixed it locally, I'll ping you when its up if you want to have another look @salimkanoun  :)

**Comment by salimkanoun** [comment]
thx @JamesAPetts , I will give a look, that's a very important feature as the MPR wasn't really usable without these crosshairs (you get often lost without crosshairs)

**Comment by JamesAPetts** [comment]
Should be up now after netlify rebuilds (or you can pull locally and check).

**Comment by salimkanoun** [comment]
Great ! Much better.

One question, the cross hair seems to be relative to the image, when you zoom In / Out you have the interaction dot moving out the field of view, and possible land on the center of the screen (which is disturbing). 

Did you considered fixing the interation dot at a fix % of the viewport axis (ex 25 % - 75%) this way the dots will stay accessible no matter of the applied zoom and will never cover the center of the image ? 

image
image

**Comment by JamesAPetts** [comment]
Good points, for now we need to merge this, but feel free to make a follow up issue with feedback.

**Pull request merged**
