### PR TITLE
Feat/print

### PR DESCRIPTION
**Pull request by rsharma0011**
### PR Checklist

- [ ] Brief description of changes
- [ ] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by rsharma0011** [comment]
Hi @dannyrb  could you review my PR?

**Comment by joweste** [comment]
Hi, 

How could I enable print feat into ohif embed into a webpage?

**Comment by dannyrb** [comment]
@rsharma0011, does this provide a better experience or satisfy a problem our current "snapshot" tool does not?

@joweste, does the current snapshot/print functionality not work for your use case? If so, can you open a new issue with steps to reproduce the issue, and your expectation of the behavior versus the actual behavior.

**Comment by rsharma0011** [comment]
@dannyrb I have added screenshot please check










[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

**Comment by joweste** [comment]
@dannyrb  Thank you. How could I make the Full Layout and Print submenu to show in my ohif? 
Do I have to download what ohif version?

**Pull request closed without merging**
