### PR TITLE
Display support for measurements from DICOM Structured Reports

### PR DESCRIPTION
**Pull request by galelis**
This pull request adds:
- Limited DICOM-SR read support for [TID 1500 Measurement Report](http://dicom.nema.org/medical/dicom/current/output/html/part16.html#sect_TID_1500)
- Sidebar UI - Measurement table to display length measurement read in from the structured report
- Measurement sidebar and limited SR read support for the Standalone Viewer

It changes:
- Sidebar UI - Removes protocol editor from the UI. The components remain in the protocol engine package, but are not used by default

**Note:** This is the first step in the process of supporting DICOM Structured Reports for all measurement types. At this stage we only support Length measurements.

Left for future PRs:
- Storage of created / edited measurements (C-STORE and STOW-RS)
- Support for other measurement types

### CODE REVIEW

**Comment by pieper** [comment]
Hi @galelis is this ready for review and testing?  Could you put it on a heroku site for testing?

Thanks,
Steve

**Comment by galelis** [comment]
@pieper Hi Steve,
Yeah, we are reviewing and testing, I have fixed a few callouts and introduce the table into Standaloneviewer as well. 
Also create new test environments if you want to test: 

http://ohifviewer-tablev1.herokuapp.com/
https://standaloneviewer.herokuapp.com/

For standalone I had to create a json ile for test, so we can use this link:
https://standaloneviewer.herokuapp.com/?url=https://raw.githubusercontent.com/galelis/testData/master/studyWithMeasurements.json

Let me know if you see any issue.

**Comment by pieper** [comment]
Hi @galelis great, this makes it much easier to test 👍 

A few quick things:
* I notice that the measurements doesn't auto-open anymore.  Was this on purpose?
* @swederik told me he asked you to remove the store but maybe we should still have it on the ohifviewer and not on standalone?  I like being able to test the roundtrip and show it to collaborators.  CSV and PDF export are also impressive to show people.
* I can now edit the description (nice!) but the input field isn't focused - it would be good to focus it when the dialog is popped up.

Otherwise it seems to be working as expected.

**Comment by swederik** [comment]
Can we keep store for the next PR? This one is huge enough already, it's hard enough to review it as it is.

**Comment by pieper** [comment]
No problem holding off stow for another PR.  Just want to be sure we don't lose it - maybe once this is in master switch over the heroku demo to include the stow options.

**Pull request merged**
