### PR TITLE
Handle missing ReferencedInstanceSequence attribute

### PR DESCRIPTION
**Pull request by paulineribeyre**
### PR Checklist

- [ ] Brief description of changes
- [ ] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

---
My team ran into this error when loading a study with a missing "0008,114A" (`ReferencedInstanceSequence`) attribute: `Cannot read properties of undefined (reading 'Value')` at `referencedInstanceSequenceRaw.Value.forEach...`.

According to the DICOM spec, this attribute is optional, so we made this change and our study loads fine.

### CODE REVIEW

**Comment by sedghi** [comment]
@igoroctaviano Can you please review this? Thanks

**Review by igoroctaviano — APPROVED** [review]
LGTM 👍

**Comment by sedghi** [comment]
@GitanjaliChhetri If you are happy as well, can we please merge this?

**Comment by GitanjaliChhetri** [comment]
> @GitanjaliChhetri If you are happy as well, can we please merge this?

yes, looks good.

**Pull request merged**
