### PR TITLE
feat(@ohif/extension-vtk): Update app to include basic MPR with VTK

### PR DESCRIPTION
**Pull request by swederik**

### CODE REVIEW

**Comment by jacklau88** [comment]
nice job.

**Comment by pieper** [comment]
Looking great!

**Comment by swederik** [comment]
There are about a million issues remaining with it. I'll be creating a big thread for them so we can slowly chip away.

**Comment by pieper** [comment]
Yeah, I noticed an issue or two (or a maybe a million : )  But still it's a big step in the right direction.

**Pull request merged**
