### PR TITLE
Feat: Add error boundaries #1729

### PR DESCRIPTION
**Pull request by igoroctaviano**
#1729

Adds a new Error Boundary component to UI library and adds error boundaries to the following components by default:
- Main Viewer
- Side Panels
- All extensions
- All routes
- Toolbar
- App (root)

### PR Checklist

- [x] Brief description of changes
- [x] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@dannyrb we can fine-tune the error messages, the way we display them and if what data should be displayed (currently its error message + stack).

**Comment by JamesAPetts** [comment]
@igoroctaviano  @dannyrb , is this feature complete, in that it can be merged and other comments in #1729 can be implemented in another ticket?

**Comment by dannyrb** [comment]
@igoroctaviano, or whoever wraps this up, the only thing I would change is where we use the ErrorBoundaries. Extensions shouldn't have to think about error boundaries as a concern, and the application likely wants to handle them in a consistent way. So offload the concern to the `Viewer` project.

This means, when we pull the extension's component in via the ExtensionManager in the `platform/viewer` project, wrap that integration/render point with an ErrorBoundary.

**Comment by JamesAPetts** [comment]
Finished in #1764.

**Pull request closed without merging**
