### PR TITLE
fix docker-compose and dockerfile for keycloak

### PR DESCRIPTION
**Pull request by toj11001**
### PR Checklist

- [x] Brief description of changes
- [x] Links to any relevant issues
- [x] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [x] `@mention` a maintainer to request a review

## Description
I updated the docker-compose and the dockerfile for the Orthanc Keycloak recipe to the new folder structure since it wasn't working in the current state. For the dockerfile build stage I took almost everything over from the root Dockerfile which was work and in the deployment stage I kept the openresty config and only update the path to the static output files from the build.

This should also solve the build problems from #1757, but the whole setup still isn't working yet. I can can get a token for the viewer at `localhost/` but when going to `/pacs` the nginx throws an error, which I'm not sure about yet.
```
accessing discovery url (http://localhost/auth/realms/ohif/.well-known/openid-configuration) failed: localhost could not be resolved (3: Host not found)
```
Could you please have a look at my changes @dannyrb  and any thoughts why I get the error message for the secured routes?

Cheers!

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by toj11001** [comment]
@dannyrb: any updates regarding a merge?

**Review by sedghi — APPROVED** [review]

**Comment by sedghi** [comment]
Closing and reOpening for netlify checks

**Comment by toj11001** [comment]
@sedghi would you be able to merge this PR please?

**Comment by sedghi** [comment]
@GitanjaliChhetri @igoroctaviano Could one of you guys please take a look at this?

**Comment by sedghi** [comment]
we updated all the recipes recently, please see if the issue still persists

**Pull request closed without merging**
