### PR TITLE
fixed Fusion_Viewport to allow displaySets to be changed

### PR DESCRIPTION
**Pull request by Sofien-Sellami**
### Context
This pull request addresses an issue where the fusion viewport does not refresh and match correctly when dragging and dropping CT and PT displaySets. The problem arises because the volumes added do not share the same FrameOfReferenceUID. Additionally, the displaySetMatchDetail of the fusion viewport  is not updated with the new displaySetInstanceUID, further exacerbating the issue.

### Changes & Results
- Modified the displaySetMatchDetail to update the displaySetInstanceUID with the appropriate value.

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by wayfarer3130** [comment]
Could you enable the series tray, but closed by default?  That way we can test this.  Also update the branch.

**Review by wayfarer3130 — APPROVED** [review]
LGTM now.

**Review by wayfarer3130 — CHANGES_REQUESTED** [review]
Sorry, marked the wrong issue.  Would like to see this with the series tray enabled but closed.
Dan approved this with it closed.

**Comment by salimkanoun** [comment]
@wayfarer3130 he add the panel but the deploy preview is in a cancelled state, however it's workin locally

**Review by wayfarer3130 — APPROVED** [review]
Looks good now - tested locally and it runs fine.

**Pull request merged**
