### PR TITLE
fix of hardcoded url

### PR DESCRIPTION
**Pull request by pavertomato**
[#585]

### CODE REVIEW

**Comment by dannyrb** [comment]
This seems pretty straightforward, and I can see the value. Thanks for the PR -- I'll merge after these tests run.

**Comment by pavertomato** [comment]
> This seems pretty straightforward, and I can see the value. Thanks for the PR -- I'll merge after these tests run.

@swederik had some doubts about it, i think it's better to wait for his opinion before merge

**Comment by swederik** [comment]
Yeah I was just worried that this would cause issues if you arrived at e.g. viewer.ohif.org/studylist or something. This is better than what we have now though so I'll merge it and we can go from there. Thanks!

**Comment by swederik** [comment]
TODO: switch to `${window.location.protocol}//${window.location.host}`

**Comment by dannyrb** [comment]
@all-contributors, please add @pavertomato for this code

**Pull request merged**
