### PR TITLE
feat: Add 1:1 scale hanging protocol

### PR DESCRIPTION
**Pull request by wayfarer3130**
This feature adds the display area setting to the hanging protocol, and then uses it to create a 1:1 scale hanging protocol.

This needs PR https://github.com/cornerstonejs/cornerstone3D/pull/755 to be set as the CS3D version for core, but
is otherwise ready to go.

### Context

Having a 1:1 scale hanging protocol allows testing/viewing of images without scaling, which allows testing of the rendering position.

### Changes & Results

Change the thumbnail to use the new rendering options to set the thumbnail size
Add hpScale as a hanging protocol
Add automated tests for image consistency/comparison

### Testing

Display the e2e test environment pages for the TG-18 resolution or general purpose tests with the hangingProtocolId=@ohif/hpScale
You should be able to see the vertical and horizontal bars on the test pattern

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by francomotta** [comment]
Hi @wayfarer3130 ,

   I test your code and show a message error when try open a study.

**Comment by wayfarer3130** [comment]
@francomotta - you need to link the appropriate CS3D build into it as there are changes in the stack viewport that are required to make this work.

**Comment by wayfarer3130** [comment]
@francomotta - I will link the required changes into this issue once we have official builds.  Otherwise, you need to folllow the OHIF instructions on how to link in CS3D

**Comment by francomotta** [comment]
> @francomotta - I will link the required changes into this issue once we have official builds.  Otherwise, you need to folllow the OHIF instructions on how to link in CS3D
> 
> 

I'm new and trying to understand the project structure. Can you help me ? I realize that few people have the desire to help. the vast majority ignore the mentions, basic errors. I have a post-processing workstation and I'm thinking about converting some plugins to OHIF. (fusion, perfusion, CTA, QCA).

**Comment by wayfarer3130** [comment]
@francomotta - you should be able to pull the current version now and test it.

**Comment by wayfarer3130** [comment]
This is subsumed by the mammo hanging protocols PR

**Pull request closed without merging**
