### PR TITLE
feat(IDC-1801): Improve/harmonize segmentations panel with rtstruct and add new visibility toggles

### PR DESCRIPTION
**Pull request by igoroctaviano**
- Issue: #1801 
- This PR also fixes a bug related to #2164 where the labelmap was being updated during segment clicks.

image
image

### CODE REVIEW

**Comment by igoroctaviano** [comment]
@Punzo this one needs to be carefully tested since we have a couple of flows and this is a big refactoring of the segmentations panel. 

- Selecting overlapping segments should activate crosshair and correct labelmap.
- New Bulk visibility toggle for segmentations.
- New segmentation UI.
- All previous behavior.

Thank you in advance.

**Comment by Punzo** [comment]
Tested over IDC case 1.3.6.1.4.1.32722.99.99.203715003805996641695765332389135385095 (overlapping segments) and 1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891 (case with rstruct).

Everything looks good, I just a have a remark regarding the overlapping segments (probably this was an "issue" also before this PR):

when I disable all the visibilities of the segments, e.g.:
image

the "non-active" ones will be still visualized. Maybe (if all the segments visibilities are off) we could toggle automatically this checkbox too:
image

**Review by Punzo — APPROVED** [review]

**Comment by igoroctaviano** [comment]
> Tested over IDC case 1.3.6.1.4.1.32722.99.99.203715003805996641695765332389135385095 (overlapping segments) and 1.3.6.1.4.1.14519.5.2.1.1706.4009.192455081946878476141947586891 (case with rstruct).
> 
> Everything looks good, I just a have a remark regarding the overlapping segments (probably this was an "issue" also before this PR):
> 
> when I disable all the visibilities of the segments, e.g.:
> image
> 
> the "non-active" ones will be still visualized. Maybe (if all the segments visibilities are off) we could toggle automatically this checkbox too:
> image

Alright, just pushed, now inactive ones will be set properly. Thanks Davide.

**Comment by Punzo** [comment]
> Alright, just pushed, now inactive ones will be set properly. Thanks Davide.

Tested, now everything wroking, LGTM!

**Pull request merged**
