### PR TITLE
Update viewport state after moving the stack

### PR DESCRIPTION
**Pull request by igoroctaviano**
Comment that raised this bug: https://github.com/OHIF/Viewers/pull/1643#pullrequestreview-395252065

- Fix bug of clicking consecutive time in measurement item / rtstruct item or seg item to jump to image. If the user clicks the seg to jump after moving the stack, the viewport specific data is set but if the user moves the stack, the state continues the same because just the frame index (which is not tracked changed) so it doesn't cause a rerender in the second click. 

Related react-cornerstone-viewport PR: https://github.com/cornerstonejs/react-cornerstone-viewport/pull/78

### PR Checklist

- [x] Brief description of changes
- [ ] Links to any relevant issues
- [ ] Required status checks are passing
- [ ] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by dannyrb** [comment]
image

CI is failing

Also, if we're going to sync state for something that changes this frequently, do we need to memoize to reduce re-renders?

**Comment by igoroctaviano** [comment]
> image
> 
> CI is failing
> 
> Also, if we're going to sync state for something that changes this frequently, do we need to memoize to reduce re-renders?

@dannyrb not sure what to memoize, this is a very specific flow which should not rerender much, maybe I'm missing something?

**Comment by igoroctaviano** [comment]
> See above ^
> 
> Also, while we're here, can you lock `react-cornerstone-viewport` to a fixed version?

Done.

**Comment by JamesAPetts** [comment]
> > image
> > CI is failing
> > Also, if we're going to sync state for something that changes this frequently, do we need to memoize to reduce re-renders?
> 
> @dannyrb not sure what to memoize, this is a very specific flow which should not rerender much, maybe I'm missing something?

@igoroctaviano  (cc: @dannyrb as you were mentioned), would you guys be able to resolve these CI issues so we can merge, this issue is important to IDC. Cheers.

**Comment by igoroctaviano** [comment]
> > > image
> > > CI is failing
> > > Also, if we're going to sync state for something that changes this frequently, do we need to memoize to reduce re-renders?
> > 
> > 
> > @dannyrb not sure what to memoize, this is a very specific flow which should not rerender much, maybe I'm missing something?
> 
> @igoroctaviano (cc: @dannyrb as you were mentioned), would you guys be able to resolve these CI issues so we can merge, this issue is important to IDC. Cheers.

@JamesAPetts I'll take a look right now. 👍

**Comment by igoroctaviano** [comment]
> > > image
> > > CI is failing
> > > Also, if we're going to sync state for something that changes this frequently, do we need to memoize to reduce re-renders?
> > 
> > 
> > @dannyrb not sure what to memoize, this is a very specific flow which should not rerender much, maybe I'm missing something?
> 
> @igoroctaviano (cc: @dannyrb as you were mentioned), would you guys be able to resolve these CI issues so we can merge, this issue is important to IDC. Cheers.

Updated with master, now its passing.

**Pull request merged**
