### PR TITLE
fix regression not showing warnings list on thumbnail for segmentations

### PR DESCRIPTION
**Pull request by Punzo**
Fix regression of segmentations thumbnails not showing the warning icon.

### CODE REVIEW

**Comment by Punzo** [comment]
@igoroctaviano could you please test and review? data for testing are at /projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.14519.5.2.1.4591.4003.241850919885310339695393380617

**Comment by Punzo** [comment]
@igoroctaviano in commit https://github.com/OHIF/Viewers/pull/2563/commits/b542b42751aec48882562228a9ff5b4fec26d4ab i have also updated dcmjs so you may test also the fix for regression https://github.com/OHIF/Viewers/issues/2003 and https://github.com/OHIF/Viewers/issues/2500

**Comment by igoroctaviano** [comment]
> @igoroctaviano could you please test and review? data for testing are at /projects/idc-dev-etl/locations/us-central1/datasets/idc-tcia/dicomStores/idc-tcia/study/1.3.6.1.4.1.14519.5.2.1.4591.4003.241850919885310339695393380617

We just rolled back the warnings for these cases?

**Review by igoroctaviano — APPROVED** [review]
@Punzo approved, but I would like to know if we just rolled back inconsistency warnings or updated them to correctly display that error when it's the case.

**Pull request merged**
