### PR TITLE
IDC-2374: Exponential backoff and retry after 500 error

### PR DESCRIPTION
**Pull request by igoroctaviano**
- DICOMWebClient issue: https://github.com/dcmjs-org/dicomweb-client/pull/36
- Issue: #2374
- Add configurable retry request hook for xhr 
- Use hook for all dicomweb-client instances
- Library used: https://github.com/tim-kos/node-retry

### CODE REVIEW

**Comment by salimkanoun** [comment]
Hi,

Is this fix able to use this issue : https://github.com/OHIF/Viewers/issues/2170
I see in the code there is a condition of retry in status code 429 or >500

Are client error code 4XX now removed from retrying ? 

Best regards,

Salim

**Comment by igoroctaviano** [comment]
> Hi,
> 
> Is this fix able to use this issue : #2170
> I see in the code there is a condition of retry in status code 429 or >500
> 
> Are client error code 4XX now removed from retrying ?
> 
> Best regards,
> 
> Salim

I think it's unrelated. dicomweb-client doesn't provide any built-in retry functionality, this PR just introduced it via request hooks which is a new change in dicomweb-client library to allow decoration of its xhr requests. 

These two status codes will be retried by default now but it's up to you to change them in your fork. I'm planning to update this PR to add a better way to config the retry via the app config file.

**Comment by Punzo** [comment]
@igoroctaviano testing this and it looks like it does not find the study list. i.e. starting default server:
image

or also using google config, by opening a study in the url:
image

looks like some undefined variables, could you please have a look? thanks!

**Comment by Punzo** [comment]
@igoroctaviano  now works if using the default config (i.e. server.dcmjs.org  server).

However using google config (i.e. google server), I get 401 errors
image (1)
image

google links in current master works

**Pull request merged**
