### PR TITLE
fix(url): series query param filtering

### PR DESCRIPTION
**Pull request by igoroctaviano**
Series filtering query param was not being propagated correctly

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Review by sedghi — CHANGES_REQUESTED** [review]
I think this change introduces some issues. It alters the behavior described [here](https://docs.ohif.org/configuration/url#seriesinstanceuids). 

The URL should be able to provide multiple SeriesInstanceUIDs and gather those series. In OHIF, the singular SeriesInstanceUID is deprecated in favor of SeriesInstanceUIDs, which is the intended functionality.

look at migration guides please

https://docs.ohif.org/migration-guide/from-3p7-to-3p8#studyinstanceuid-in-the-url-param

**Comment by igoroctaviano** [comment]
> I think this change introduces some issues. It alters the behavior described [here](https://docs.ohif.org/configuration/url#seriesinstanceuids).
> 
> The URL should be able to provide multiple SeriesInstanceUIDs and gather those series. In OHIF, the singular SeriesInstanceUID is deprecated in favor of SeriesInstanceUIDs, which is the intended functionality.
> 
> look at migration guides please
> 
> https://docs.ohif.org/migration-guide/from-3p7-to-3p8#studyinstanceuid-in-the-url-param

I have tested it and while debugging you can see that SeriesInstanceUIDs query param translates to seriesInstanceUID. Thats how it works today. Maybe because it was done like that to match dicomweb-client. Today the multi series filtering does work.

**Comment by fedorov** [comment]
@sedghi please note that the URL syntax being discussed here works fine with the version of the viewer in the latest production release we use in IDC 3.8.0-beta.64: https://viewer.imaging.datacommons.cancer.gov/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.192012426995727721871016249335309434385&SeriesInstanceUIDs=1.2.840.113654.2.55.305538394446738410906709753576946604022,1.2.276.0.7230010.3.1.3.313263360.15787.1706310178.804490

**Review by sedghi — APPROVED** [review]
Seems like we still use the SeriesInstanceUIDs internally so great!

**Pull request merged**
