### PR TITLE
[Probably Not to Merge] Highliting issues with Onboarding.css

### PR DESCRIPTION
**Pull request by salimkanoun**
Hi, there is this Onboarding.css file there are several custom class that doesn't existing in Tailwind Layers resulting in build issues,

I don't know how to fix this, however for those are blocked building OHIF, emptying onboarding.css make OHIF building again (but will probably break the new onboarding feature)

### CODE REVIEW

**Comment by sedghi** [comment]
@IbrahimCSAE can you fix this please

**Comment by IbrahimCSAE** [comment]
ill fix this in another pr, you can close this salim, thank you

**Comment by IbrahimCSAE** [comment]
i honestly dont have any issues building ohif locally on latest, and also the classes are all defined here. I don't understand the issue.

https://github.com/OHIF/Viewers/blob/master/platform/ui-next/tailwind.config.js

bg-popover is valid. wouldn't the CI fail and my local build fail? Sorry but I don't get the issue here.

@sedghi @salimkanoun

**Comment by salimkanoun** [comment]
Sorry my fault, I was missing the import of ui-next in my custom tailwind config ....

**Pull request closed without merging**
