### PR TITLE
WIP feat(SR): Add the ability to filter SRs based on selected displaySet

### PR DESCRIPTION
**Pull request by rodrigobasilio2022**
### Context

When an study has many SRs, some users prefer that only the SRs of the currently selected displyaSet are shown. This PR adds the ability to filter SRs based on active viewport display set

#### PR

- [] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [] OS: 
- [] Node version: 
- [] Browser:
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by sedghi** [comment]
can you please add before and after screenshots?

**Comment by sedghi** [comment]
@igoroctaviano and @rodrigobasilio2022, please complete the pull request (PR) description and add relevant testing data, screenshots, etc.

**Comment by igoroctaviano** [comment]
> @igoroctaviano and @rodrigobasilio2022, please complete the pull request (PR) description and add relevant testing data, screenshots, etc.

I'm working on another PR related to SCOORD3D, I'll keep this PR as WIP for now.

**Comment by igoroctaviano** [comment]
@rodrigobasilio2022 this PR was part of which issue?

**Comment by rodrigobasilio2022** [comment]
Probably this will be superseed depending on how the SCOORD3D will be defined. So probably leave it as it or close it

**Pull request closed without merging**
