### PR TITLE
fix: 🐛 Fix multiframe images

### PR DESCRIPTION
**Pull request by JamesAPetts**
Fix splitting of multiframe images into a cornerstone stack.

### CODE REVIEW

**Comment by 3833430** [comment]
e，i feel dont fix multiframe image.
when scroll next frame,not send any request to server.
only  first frame request
http://localhost:44301/api/studies/1.3.46.670589.28.26690171471530920200312015756768959/series/1.3.46.670589.28.26690171471530920200312030543633059.2.2/instances/1.3.46.670589.28.266901714715309202003120305494839702211221/frames/1

**Comment by dannyrb** [comment]
@3833430, we're seeing this as well. Investigating 🔬

**Comment by JamesAPetts** [comment]
Odd, this fixed it for a bunch of multiframe brain MR, but I see some scans are still broken, investigating.

**Comment by andreiSeer** [comment]
On master versionof OHIF the US  multi frame images does not open correctly. I tried old versions of OHIF at it worked.

**Comment by ed-morais** [comment]
Hello, @dannyrb and @JamesAPetts!
There are still some problems with the US multiframe, as shown in the image below:

Screenshot from 2021-11-23 11-11-11

I've been investigating how to solve it, but I wasn't successful
Could you guys please help me out?

Kind regards (:

**Comment by ed-morais** [comment]
Hello, @dannyrb and @JamesAPetts!
There are still some problems with the US multiframe, as shown in the image below:

Screenshot from 2021-11-23 11-11-11

I've been investigating how to solve it, but I wasn't successful
Could you guys please help me out?

Kind regards (:

**Pull request merged**
