### PR TITLE
fix: application crash if patientName is an object

### PR DESCRIPTION
**Pull request by dannyrb**
- Removes "pill" styling from modalities
- Logic to use `modalitiesInStudy` if `modality` is undefined
- Show `(empty)` if no `modality` or `modalitiesInStudy` values

### CODE REVIEW

**Comment by dannyrb** [comment]
CC: @pieper 

Still not in love with the small and medium table layouts; please don't hesitate to provide feedback. Do let me know if this resolves your `breast-diagnosis` dateset issues, or if you have other sets that are failing for you.

We may want to consider adding ["error boundaries"](https://reactjs.org/docs/error-boundaries.html) to make things like this easier to troubleshoot as we move forward.

**Comment by pieper** [comment]
Hi @dannyrb - I'm afraid the `breast-diagnosis` issue is still there with the current master. 😢

**Comment by dannyrb** [comment]
@pieper, I'm able to load this route: https://idc-sandbox-000.firebaseapp.com/projects/chc-tcia/locations/us-central1/datasets/breast-diagnosis/dicomStores/breast-diagnosis

It's working for me in FireFox and Google Chrome.

I've tried visiting it directly, and navigating to it w/ `Change DICOM Store`

For a dateset that does work, what version do you see when you click `Options` --> `About`?

If you're using Google Chrome, can you:

- Open Inspector
- Select the `Applications` tab
- Select `Service Workers`
- Try clicking `Unregister`
- Close all tabs that have sandbox open
- Open a new tab w/ the `breast-diagnosis` route

**Comment by pieper** [comment]
Weird - I'm having very odd behavior now.

* I follow your steps
* open new page with the link
* first time I try the link I get a flash of interface then a blank screen
* then if I reload the page the study list shows up
* clicking on any study the page starts loading then fails with errors below

```
react-dom.production.min.js:196 TypeError: e.replace is not a function
    at Ct (index.umd.js:2415)
    at t.value (index.umd.js:7071)
    at $o (react-dom.production.min.js:181)
    at qo (react-dom.production.min.js:180)
    at Es (react-dom.production.min.js:261)
    at kl (react-dom.production.min.js:230)
    at Ql (react-dom.production.min.js:229)
    at Bl (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
ms @ react-dom.production.min.js:196
n.callback @ react-dom.production.min.js:210
Ca @ react-dom.production.min.js:131
va @ react-dom.production.min.js:131
Dl @ react-dom.production.min.js:252
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ index.umd.js:9364
r @ cornerstone.js:7623
t.default @ cornerstone.js:4304
e @ cornerstone.js:2162
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
t.default @ cornerstone.js:2168
(anonymous) @ index.umd.js:9462
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
C @ index.umd.js:932
a @ index.umd.js:954
(anonymous) @ index.umd.js:961
(anonymous) @ index.umd.js:950
(anonymous) @ index.umd.js:9520
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ OHIFCornerstoneViewport.js:209
Promise.then (async)
value @ OHIFCornerstoneViewport.js:208
value @ OHIFCornerstoneViewport.js:216
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ asyncComponent.js:23
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
Se @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
Promise.then (async)
Se @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
r.value @ asyncComponent.js:9
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
value @ ViewerRetrieveStudyData.js:65
(anonymous) @ ViewerRetrieveStudyData.js:35
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
v @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
a @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
Promise.then (async)
v @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
a @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
(anonymous) @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
i @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
n.value @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
value @ ViewerRetrieveStudyData.js:104
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ AsyncComponent.js:23
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
o @ app.bundle.c9ff208233d553eec372.js:2
a @ app.bundle.c9ff208233d553eec372.js:2
Promise.then (async)
o @ app.bundle.c9ff208233d553eec372.js:2
a @ app.bundle.c9ff208233d553eec372.js:2
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
g @ app.bundle.c9ff208233d553eec372.js:2
a.value @ AsyncComponent.js:9
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
vl @ react-dom.production.min.js:224
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
t.handleChangeWrapper @ Subscription.js:70
m @ redux.js:220
(anonymous) @ index.js:11
r @ redux-oidc.js:1
Promise.then (async)
t.default @ redux-oidc.js:1
B @ getUserManagerForOpenIdConnectClient.js:33
value @ App.js:160
t @ App.js:81
Qa @ react-dom.production.min.js:135
qo @ react-dom.production.min.js:175
Es @ react-dom.production.min.js:261
kl @ react-dom.production.min.js:230
Ql @ react-dom.production.min.js:229
Bl @ react-dom.production.min.js:223
ml @ react-dom.production.min.js:214
iu @ react-dom.production.min.js:279
(anonymous) @ react-dom.production.min.js:285
Cl @ react-dom.production.min.js:224
cu @ react-dom.production.min.js:285
render @ react-dom.production.min.js:286
(anonymous) @ index.js:52
a @ bootstrap:68
(anonymous) @ bootstrap:244
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
react-dom.production.min.js:121 Uncaught TypeError: e.replace is not a function
    at Ct (index.umd.js:2415)
    at t.value (index.umd.js:7071)
    at $o (react-dom.production.min.js:181)
    at qo (react-dom.production.min.js:180)
    at Es (react-dom.production.min.js:261)
    at kl (react-dom.production.min.js:230)
    at Ql (react-dom.production.min.js:229)
    at Bl (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
Ct @ index.umd.js:2415
value @ index.umd.js:7071
$o @ react-dom.production.min.js:181
qo @ react-dom.production.min.js:180
Es @ react-dom.production.min.js:261
kl @ react-dom.production.min.js:230
Ql @ react-dom.production.min.js:229
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ index.umd.js:9364
r @ cornerstone.js:7623
t.default @ cornerstone.js:4304
e @ cornerstone.js:2162
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
requestAnimationFrame (async)
t.default @ cornerstone.js:4948
e @ cornerstone.js:2165
t.default @ cornerstone.js:2168
(anonymous) @ index.umd.js:9462
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
C @ index.umd.js:932
a @ index.umd.js:954
(anonymous) @ index.umd.js:961
(anonymous) @ index.umd.js:950
(anonymous) @ index.umd.js:9520
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ OHIFCornerstoneViewport.js:209
Promise.then (async)
value @ OHIFCornerstoneViewport.js:208
value @ OHIFCornerstoneViewport.js:216
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ asyncComponent.js:23
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
Se @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
Promise.then (async)
Se @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
o @ app.bundle.c9ff208233d553eec372.js:2
r.value @ asyncComponent.js:9
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
value @ ViewerRetrieveStudyData.js:65
(anonymous) @ ViewerRetrieveStudyData.js:35
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
v @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
a @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
Promise.then (async)
v @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
a @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
(anonymous) @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
i @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
n.value @ ViewerRouting.bundle.5ee7d0d56c860ff010bc.js:1
value @ ViewerRetrieveStudyData.js:104
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
ml @ react-dom.production.min.js:214
enqueueSetState @ react-dom.production.min.js:133
y.setState @ react.production.min.js:13
(anonymous) @ AsyncComponent.js:23
u @ runtime.js:45
(anonymous) @ runtime.js:271
forEach.e.<computed> @ runtime.js:97
o @ app.bundle.c9ff208233d553eec372.js:2
a @ app.bundle.c9ff208233d553eec372.js:2
Promise.then (async)
o @ app.bundle.c9ff208233d553eec372.js:2
a @ app.bundle.c9ff208233d553eec372.js:2
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
g @ app.bundle.c9ff208233d553eec372.js:2
a.value @ AsyncComponent.js:9
Dl @ react-dom.production.min.js:251
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
Tl @ react-dom.production.min.js:244
Bl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Pi @ react-dom.production.min.js:120
qi @ react-dom.production.min.js:121
Ki @ react-dom.production.min.js:120
vl @ react-dom.production.min.js:224
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
t.handleChangeWrapper @ Subscription.js:70
m @ redux.js:220
(anonymous) @ index.js:11
r @ redux-oidc.js:1
Promise.then (async)
t.default @ redux-oidc.js:1
B @ getUserManagerForOpenIdConnectClient.js:33
value @ App.js:160
t @ App.js:81
Qa @ react-dom.production.min.js:135
qo @ react-dom.production.min.js:175
Es @ react-dom.production.min.js:261
kl @ react-dom.production.min.js:230
Ql @ react-dom.production.min.js:229
Bl @ react-dom.production.min.js:223
ml @ react-dom.production.min.js:214
iu @ react-dom.production.min.js:279
(anonymous) @ react-dom.production.min.js:285
Cl @ react-dom.production.min.js:224
cu @ react-dom.production.min.js:285
render @ react-dom.production.min.js:286
(anonymous) @ index.js:52
a @ bootstrap:68
(anonymous) @ bootstrap:244
(anonymous) @ app.bundle.c9ff208233d553eec372.js:2
DevTools failed to parse SourceMap: https://idc-sandbox-000.firebaseapp.com/434dd146697bf197b774.worker.js.map
oidc-client.min.js:47 Uncaught (in promise) Error: Frame window timed out
    at e._error (oidc-client.min.js:47)
    at e._timeout (oidc-client.min.js:47)
```

**Comment by dannyrb** [comment]
@pieper, fun stuff.
We should probably get map files on the IDC SandBox so exceptions are more verbose.
Having error boundaries would also allow for a more graceful failure.
This one is the `formatPN` function on the `CornerstoneViewport` failing because it expects `patientName` to be a string, but is receiving an empty object.

We handled the issue for the list route, but the viewer route also expects a string in several situations. I'll create a new issue and get back to you on this one. Instead of a band-aid, I want to look into why we're receiving an object and how best to handle the situation.

The hoops I had you jump through are because we're using a Service Worker now. This means that the "OHIF Application" is cached on the local machine (for subsequent visits), and the local application files are used for a faster initial page load.

**Comment by pieper** [comment]
Thanks for your help!  Let me know if I should do any more testing.  (BTWFYI, the new IDC labels are a test to keep track of what things IDC needs - I think they are going to prove that IDC gets way more than its money's worth from OHIF!).

**Pull request merged**
