### PR TITLE
feat(ViewportActionBar and CinePlayer): Add new design for action bar and cine player

### PR DESCRIPTION
**Pull request by jbocce**
This pull request is for merging the feature branch feat/viewport-actionbar-enhancements to v3-stable.

Detailed PRs have already been performed on the feature branch. In particular...

- https://github.com/OHIF/Viewers/pull/3198
- https://github.com/OHIF/Viewers/pull/3186

This pull request is simply the merging of the changes in those PRs to v3-stable

### CODE REVIEW

**Comment by sedghi** [comment]
great work indeed. 

Could you please look into these

1. The arrows don't go to hide when minimize happens sometimes when there is no focus?

[1c74d097-2258-4ed4-a3f4-81289cade88a.webm](https://user-images.githubusercontent.com/7490180/221885387-fe86ae2d-7caf-4fad-8e0d-bf22c7a7d23e.webm)

2. The tooltip for CINE is too low, almost touching the text
image

3. The tool tip hover don't stay when moving to the extremes 
[ae1d193c-cb36-46a2-a3ab-1b50b456b9a8.webm](https://user-images.githubusercontent.com/7490180/221886199-9aac736c-34d3-4333-8b5c-274066e9c155.webm)

4. I asked Erik and he also thinks < > should navigate in the measurements of the current viewport being selected. It is an easy fix since you just need to filter the measurement [here](https://github.com/OHIF/Viewers/blob/v3-stable/extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx#L278-L329), can we have that for this PR as well?

**Comment by jbocce** [comment]
> great work indeed.
> 
> Could you please look into these
> 
> 1. The arrows don't go to hide when minimize happens sometimes when there is no focus?
> 
> 2. The tooltip for CINE is too low, almost touching the text
>    image
> 3. The tool tip hover don't stay when moving to the extremes
>    [ae1d193c-cb36-46a2-a3ab-1b50b456b9a8.webm](https://user-images.githubusercontent.com/7490180/221886199-9aac736c-34d3-4333-8b5c-274066e9c155.webm)
> 4. I asked Erik and he also thinks < > should navigate in the measurements of the current viewport being selected. It is an easy fix since you just need to filter the measurement [here](https://github.com/OHIF/Viewers/blob/v3-stable/extensions/measurement-tracking/src/viewports/TrackedCornerstoneViewport.tsx#L278-L329), can we have that for this PR as well?

Thanks for the feedback Alireza. I will address each of these in the next commit. In summary...

1. I was not correctly using the DOM ref in the React component - I incorrectly was using the ref as if setting the ref would cause a render which I fully new better, but stuff happens. I will store the DOM element in state as the ref changes and all will be good.
2. I have moved the tooltip up. However there is only so high it can go because if it goes too high there will be a gap between the hover area and the the tooltip and the tooltip will disappear as the mouse travels from the hover area to the tooltip.
3. From the video you posted it was evident that the mouse was travelling out the side in to the < > buttons' area which was NOT a hover area. Now the hover area includes the FPS text plus the < > buttons.
4. I think I have added the correct logic.

**Comment by sedghi** [comment]
Found more 

image

is not the previous color

- Toolbar color is different 

https://user-images.githubusercontent.com/7490180/221958649-26cf7fb7-943d-4cb1-8a9b-8fb5ba666f07.mp4

**Comment by jbocce** [comment]
> Found more
> 
> image
> 
> is not the previous color
> 
> * Toolbar color is different

You have a good eye @sedghi! These regressions were caused by an update to tailwind 3.2.7. There is no actual need for the update and since there were so many UI regressions because of the update, I think it is best to rollback to 3.2.4 - especially considering there are likely more regressions that are not easy to spot at this point in time.

**Review by sedghi — APPROVED** [review]
Looks great! Thanks

**Pull request merged**
