### PR TITLE
Added an extension for downloading an entire study

### PR DESCRIPTION
**Pull request by Christian-e-S**
related issue: https://github.com/OHIF/Viewers/issues/2430#issue-907754649

* User can trigger the download of a complete study, via toolbar button
* User gets detailed status information in a modal view 
* * Individual steps (downloading, zipping, saving)
* * a pull request for the dicomweb-client client has been issued. With this version the user sees also the progress of the download in terms of downloaded bytes (see https://github.com/dcmjs-org/dicomweb-client/pull/44#issue-676285054).

  

- [x] Brief description of changes
- [x] Links to any relevant issues
- [x] Required status checks are passing
- [x] User cases if changes impact the user's experience
- [ ] `@mention` a maintainer to request a review

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by igoroctaviano** [comment]
Hey @Christian-e-S, great job here :) 🎖️ 

So, I just quickly tested the feature and it seems to be working fine. We have some of this logic in another extension (debugging) but I think it its currently broken, maybe we are better off accepting this separate extension and dumping the old download logic from debugging (what do you think @swederik?)

I have some comments regarding the modal though:
Screen Shot 2021-07-07 at 08 42 11

- When clicking to open the modal, it downloads right away but I think we should add a 'download' button there to avoid clicking the button in the toolbar by mistake and starting a huge downloading request in the background
- The size was not updated after downloading 
- There's no visible loading indicator, I thought it was stuck with a blank status: ...
- You can leverage the notification service to display notifications e.g. 'Study downloaded successfully' or something 
## Extras
- What about adding options in the modal to download display set (series) based or instance-based (we can tackle this in another branch)
- Another extra case that is really not important right now (just thought about it): Adding an option to disable and enable a save button in the viewport overlay so users can download the active viewport

**Review by igoroctaviano — CHANGES_REQUESTED** [review]
Great job 🎖️  I just left a comment, let's discuss it first 😄

**Comment by Christian-e-S** [comment]
Hey @igoroctaviano!

Thank you very much for your review!

Please find my comment below:

> Hey @Christian-e-S, great job here :) 🎖️
> 
> So, I just quickly tested the feature and it seems to be working fine. We have some of this logic in another extension (debugging) but I think it its currently broken, maybe we are better off accepting this separate extension and dumping the old download logic from debugging (what do you think @swederik?)
> 
> I have some comments regarding the modal though:
> Screen Shot 2021-07-07 at 08 42 11
> 
> * I think toolbar button should not be enabled in master by default (@pieper @swederik do we have liability concerns?)

I agree, this makes absolutely sense!

> * When clicking to open the modal, it downloads right away but I think we should add a 'download' button there to avoid clicking the button in the toolbar by mistake and starting a huge downloading request in the background

We had it like this, but users complained about the additional click. In some use cases, users use the online viewer just for previewing images, and then download the series to be able to use the specific features of the tool that they are used to, so downloading becomes their major use case and they want to have it efficient.

> * The size was not updated after downloading

This works only with a recent commit of the dicomweb-client https://github.com/dcmjs-org/dicomweb-client/commit/c292726a421cd84e6a34aec4e72fbbad3c87621c that was created from my pull request to the dicomweb-client repository. This is required to get progress information in terms of bytes downloaded.

Should we wait until this gets into the next release of dicomweb-client?

image


> * There's no visible loading indicator, I thought it was stuck with a blank status: ...

See comment above. With the latest master branch of the dicomweb-client you can see the transferred bytes progressing, during the download, which gives a good indication:

image

image



> * You can leverage the notification service to display notifications e.g. 'Study downloaded successfully' or something

Agreed

> 
> ## Extras
> * What about adding options in the modal to download display set (series) based or instance-based (we can tackle this in another branch)
> * Another extra case that is really not important right now (just thought about it): Adding an option to disable and enable a save button in the viewport overlay so users can download the active viewport

I like these ideas.

**Comment by sedghi** [comment]
@igoroctaviano what is the status on this?

**Comment by igoroctaviano** [comment]
@sedghi codewise LGTM but we need to check if we want to merge it (I know that there are some implications to having an easy download button in a viewer).

**Comment by sedghi** [comment]
base has changed, read more here https://github.com/OHIF/Viewers/issues/3477

**Comment by threehappypenguins** [comment]
> @Christian-e-S , do you have this extension to v3? rgds and great job.

Did you ever try this with v3? If so, how did you go about it? I don't even know how to get started with adding the extension.

**Comment by sedghi** [comment]
@threehappypenguins No we haven't done it in v3

**Comment by sedghi** [comment]
I'm closing this as not planned because it's related to v2-legacy. Keeping it open might suggest we support fixing issues in v2-legacy. If this problem persists in v3, please open an issue or, even better, provide a fix for v3.

**Pull request closed without merging**
