### PR TITLE
feat: improve disableEditing flag

### PR DESCRIPTION
**Pull request by pedrokohler**
### Context

- #3863

Setting the "disableEditing" flag to true is now going to stop the user from editing SR measurements, saving new SRs and exporting measurements.

### Changes & Results

Before:

https://github.com/OHIF/Viewers/assets/22822446/e8b2b993-ab34-4083-9345-41576119268b

After:

https://github.com/OHIF/Viewers/assets/22822446/842270fd-0b9a-4297-8906-9aa53b51e6d4

### Testing

Manually tested.

#### PR

- [X] My Pull Request title is descriptive, accurate and follows the
  semantic-release format and guidelines.

#### Code

- [X] My code has been well-documented (function documentation, inline comments,
  etc.)

#### Public Documentation Updates

- [] The documentation page has been updated as necessary for any public API
  additions or removals.

#### Tested Environment

- [X] OS: MacOS 14.2.1 (23C71)
- [X] Node version: 18.16.1
- [X] Browser: Chrome  119.0.6045.105
  

[blog]: https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/
[script]: https://github.com/jklukas/git-push-fork-to-upstream-branch

### CODE REVIEW

**Comment by pedrokohler** [comment]
Linked to https://github.com/OHIF/Viewers/issues/3863

**Comment by igoroctaviano** [comment]
@sedghi Now that the disableEditing property also disables saving/downloading reports and editing of SR measurements, what do you think about renaming it to readOnly instead? Later we could disable more features in the viewer that could cause medical data side effects. I think this property can be useful for people using the viewer just for passively viewing medical data/results preventing modifications.

**Comment by sedghi** [comment]
@igoroctaviano read-only sounds like they shouldn't be able to annotate either, so it would be odd if the viewer is in read only but they can measure

**Review by igoroctaviano — APPROVED** [review]
LGTM @sedghi

**Review by sedghi — APPROVED** [review]
Makes sense, thanks

**Pull request merged**
